// ====== Currency -> Country lookup ======
// Maps ISO currency codes to a display country/region name and flag emoji,
// so the dropdowns and conversion result can show which country a currency
// belongs to (not just its name, which isn't always obvious - e.g. "Birr",
// "Kwacha", "Dalasi").
// A few currencies are shared across multiple countries (EUR, XOF, XCD,
// etc.) - those use a region label instead of a single country.
// Codes not present here (e.g. cryptocurrencies, precious metals like gold/
// silver) simply won't show a country tag - the app degrades gracefully.
const CURRENCY_COUNTRY_MAP = {
    AED: { country: "United Arab Emirates", flag: "🇦🇪" },
    AFN: { country: "Afghanistan", flag: "🇦🇫" },
    ALL: { country: "Albania", flag: "🇦🇱" },
    AMD: { country: "Armenia", flag: "🇦🇲" },
    ANG: { country: "Curaçao & Sint Maarten", flag: "🇨🇼" },
    AOA: { country: "Angola", flag: "🇦🇴" },
    ARS: { country: "Argentina", flag: "🇦🇷" },
    AUD: { country: "Australia", flag: "🇦🇺" },
    AWG: { country: "Aruba", flag: "🇦🇼" },
    AZN: { country: "Azerbaijan", flag: "🇦🇿" },
    BAM: { country: "Bosnia & Herzegovina", flag: "🇧🇦" },
    BBD: { country: "Barbados", flag: "🇧🇧" },
    BDT: { country: "Bangladesh", flag: "🇧🇩" },
    BGN: { country: "Bulgaria", flag: "🇧🇬" },
    BHD: { country: "Bahrain", flag: "🇧🇭" },
    BIF: { country: "Burundi", flag: "🇧🇮" },
    BMD: { country: "Bermuda", flag: "🇧🇲" },
    BND: { country: "Brunei", flag: "🇧🇳" },
    BOB: { country: "Bolivia", flag: "🇧🇴" },
    BRL: { country: "Brazil", flag: "🇧🇷" },
    BSD: { country: "Bahamas", flag: "🇧🇸" },
    BTN: { country: "Bhutan", flag: "🇧🇹" },
    BWP: { country: "Botswana", flag: "🇧🇼" },
    BYN: { country: "Belarus", flag: "🇧🇾" },
    BZD: { country: "Belize", flag: "🇧🇿" },
    CAD: { country: "Canada", flag: "🇨🇦" },
    CDF: { country: "DR Congo", flag: "🇨🇩" },
    CHF: { country: "Switzerland", flag: "🇨🇭" },
    CLP: { country: "Chile", flag: "🇨🇱" },
    CNY: { country: "China", flag: "🇨🇳" },
    COP: { country: "Colombia", flag: "🇨🇴" },
    CRC: { country: "Costa Rica", flag: "🇨🇷" },
    CUP: { country: "Cuba", flag: "🇨🇺" },
    CVE: { country: "Cape Verde", flag: "🇨🇻" },
    CZK: { country: "Czech Republic", flag: "🇨🇿" },
    DJF: { country: "Djibouti", flag: "🇩🇯" },
    DKK: { country: "Denmark", flag: "🇩🇰" },
    DOP: { country: "Dominican Republic", flag: "🇩🇴" },
    DZD: { country: "Algeria", flag: "🇩🇿" },
    EGP: { country: "Egypt", flag: "🇪🇬" },
    ERN: { country: "Eritrea", flag: "🇪🇷" },
    ETB: { country: "Ethiopia", flag: "🇪🇹" },
    EUR: { country: "Eurozone", flag: "🇪🇺" },
    FJD: { country: "Fiji", flag: "🇫🇯" },
    FKP: { country: "Falkland Islands", flag: "🇫🇰" },
    GBP: { country: "United Kingdom", flag: "🇬🇧" },
    GEL: { country: "Georgia", flag: "🇬🇪" },
    GHS: { country: "Ghana", flag: "🇬🇭" },
    GIP: { country: "Gibraltar", flag: "🇬🇮" },
    GMD: { country: "Gambia", flag: "🇬🇲" },
    GNF: { country: "Guinea", flag: "🇬🇳" },
    GTQ: { country: "Guatemala", flag: "🇬🇹" },
    GYD: { country: "Guyana", flag: "🇬🇾" },
    HKD: { country: "Hong Kong", flag: "🇭🇰" },
    HNL: { country: "Honduras", flag: "🇭🇳" },
    HRK: { country: "Croatia", flag: "🇭🇷" },
    HTG: { country: "Haiti", flag: "🇭🇹" },
    HUF: { country: "Hungary", flag: "🇭🇺" },
    IDR: { country: "Indonesia", flag: "🇮🇩" },
    ILS: { country: "Israel", flag: "🇮🇱" },
    INR: { country: "India", flag: "🇮🇳" },
    IQD: { country: "Iraq", flag: "🇮🇶" },
    IRR: { country: "Iran", flag: "🇮🇷" },
    ISK: { country: "Iceland", flag: "🇮🇸" },
    JMD: { country: "Jamaica", flag: "🇯🇲" },
    JOD: { country: "Jordan", flag: "🇯🇴" },
    JPY: { country: "Japan", flag: "🇯🇵" },
    KES: { country: "Kenya", flag: "🇰🇪" },
    KGS: { country: "Kyrgyzstan", flag: "🇰🇬" },
    KHR: { country: "Cambodia", flag: "🇰🇭" },
    KMF: { country: "Comoros", flag: "🇰🇲" },
    KPW: { country: "North Korea", flag: "🇰🇵" },
    KRW: { country: "South Korea", flag: "🇰🇷" },
    KWD: { country: "Kuwait", flag: "🇰🇼" },
    KYD: { country: "Cayman Islands", flag: "🇰🇾" },
    KZT: { country: "Kazakhstan", flag: "🇰🇿" },
    LAK: { country: "Laos", flag: "🇱🇦" },
    LBP: { country: "Lebanon", flag: "🇱🇧" },
    LKR: { country: "Sri Lanka", flag: "🇱🇰" },
    LRD: { country: "Liberia", flag: "🇱🇷" },
    LSL: { country: "Lesotho", flag: "🇱🇸" },
    LYD: { country: "Libya", flag: "🇱🇾" },
    MAD: { country: "Morocco", flag: "🇲🇦" },
    MDL: { country: "Moldova", flag: "🇲🇩" },
    MGA: { country: "Madagascar", flag: "🇲🇬" },
    MKD: { country: "North Macedonia", flag: "🇲🇰" },
    MMK: { country: "Myanmar", flag: "🇲🇲" },
    MNT: { country: "Mongolia", flag: "🇲🇳" },
    MOP: { country: "Macau", flag: "🇲🇴" },
    MRU: { country: "Mauritania", flag: "🇲🇷" },
    MUR: { country: "Mauritius", flag: "🇲🇺" },
    MVR: { country: "Maldives", flag: "🇲🇻" },
    MWK: { country: "Malawi", flag: "🇲🇼" },
    MXN: { country: "Mexico", flag: "🇲🇽" },
    MYR: { country: "Malaysia", flag: "🇲🇾" },
    MZN: { country: "Mozambique", flag: "🇲🇿" },
    NAD: { country: "Namibia", flag: "🇳🇦" },
    NGN: { country: "Nigeria", flag: "🇳🇬" },
    NIO: { country: "Nicaragua", flag: "🇳🇮" },
    NOK: { country: "Norway", flag: "🇳🇴" },
    NPR: { country: "Nepal", flag: "🇳🇵" },
    NZD: { country: "New Zealand", flag: "🇳🇿" },
    OMR: { country: "Oman", flag: "🇴🇲" },
    PAB: { country: "Panama", flag: "🇵🇦" },
    PEN: { country: "Peru", flag: "🇵🇪" },
    PGK: { country: "Papua New Guinea", flag: "🇵🇬" },
    PHP: { country: "Philippines", flag: "🇵🇭" },
    PKR: { country: "Pakistan", flag: "🇵🇰" },
    PLN: { country: "Poland", flag: "🇵🇱" },
    PYG: { country: "Paraguay", flag: "🇵🇾" },
    QAR: { country: "Qatar", flag: "🇶🇦" },
    RON: { country: "Romania", flag: "🇷🇴" },
    RSD: { country: "Serbia", flag: "🇷🇸" },
    RUB: { country: "Russia", flag: "🇷🇺" },
    RWF: { country: "Rwanda", flag: "🇷🇼" },
    SAR: { country: "Saudi Arabia", flag: "🇸🇦" },
    SBD: { country: "Solomon Islands", flag: "🇸🇧" },
    SCR: { country: "Seychelles", flag: "🇸🇨" },
    SDG: { country: "Sudan", flag: "🇸🇩" },
    SEK: { country: "Sweden", flag: "🇸🇪" },
    SGD: { country: "Singapore", flag: "🇸🇬" },
    SHP: { country: "Saint Helena", flag: "🇸🇭" },
    SLE: { country: "Sierra Leone", flag: "🇸🇱" },
    SOS: { country: "Somalia", flag: "🇸🇴" },
    SRD: { country: "Suriname", flag: "🇸🇷" },
    SSP: { country: "South Sudan", flag: "🇸🇸" },
    STN: { country: "São Tomé & Príncipe", flag: "🇸🇹" },
    SYP: { country: "Syria", flag: "🇸🇾" },
    SZL: { country: "Eswatini", flag: "🇸🇿" },
    THB: { country: "Thailand", flag: "🇹🇭" },
    TJS: { country: "Tajikistan", flag: "🇹🇯" },
    TMT: { country: "Turkmenistan", flag: "🇹🇲" },
    TND: { country: "Tunisia", flag: "🇹🇳" },
    TOP: { country: "Tonga", flag: "🇹🇴" },
    TRY: { country: "Turkey", flag: "🇹🇷" },
    TTD: { country: "Trinidad & Tobago", flag: "🇹🇹" },
    TWD: { country: "Taiwan", flag: "🇹🇼" },
    TZS: { country: "Tanzania", flag: "🇹🇿" },
    UAH: { country: "Ukraine", flag: "🇺🇦" },
    UGX: { country: "Uganda", flag: "🇺🇬" },
    USD: { country: "United States", flag: "🇺🇸" },
    UYU: { country: "Uruguay", flag: "🇺🇾" },
    UZS: { country: "Uzbekistan", flag: "🇺🇿" },
    VES: { country: "Venezuela", flag: "🇻🇪" },
    VND: { country: "Vietnam", flag: "🇻🇳" },
    VUV: { country: "Vanuatu", flag: "🇻🇺" },
    WST: { country: "Samoa", flag: "🇼🇸" },
    XAF: { country: "Central Africa (CEMAC)", flag: "🌍" },
    XCD: { country: "Eastern Caribbean", flag: "🌴" },
    XOF: { country: "West Africa (UEMOA)", flag: "🌍" },
    XPF: { country: "French Polynesia", flag: "🇵🇫" },
    YER: { country: "Yemen", flag: "🇾🇪" },
    ZAR: { country: "South Africa", flag: "🇿🇦" },
    ZMW: { country: "Zambia", flag: "🇿🇲" },
    ZWL: { country: "Zimbabwe", flag: "🇿🇼" }
};

// Returns { country, flag } for a currency code, or null if not in the map
// (e.g. cryptocurrencies, precious metals like gold/silver) - callers should
// handle null by simply omitting the country tag.
function getCurrencyCountry(code) {
    return CURRENCY_COUNTRY_MAP[code.toUpperCase()] || null;
}
